### ISSUE TITLE
Source code?

### ISSUE THREAD

**Issue by mid-kid** [clockworkpi/apt#3]
I'm wondering where I can find the packaging sources for the various packages in this repository. Stuff like [uconsole-4g-util](https://github.com/clockworkpi/apt/tree/main/debian/pool/main/u/uconsole-4g-util).

**Comment by cuu** [comment]
packaging sources? what you mean

you can download the https://github.com/clockworkpi/apt/raw/main/debian/pool/main/u/uconsole-4g-util/uconsole-4g-util_0.1_arm64.deb

to your linux computer 

then use

```
ar x  uconsole-4g-util_0.1_arm64.deb
```

to uncompress the deb file,then you can have everything

control.tar.gz 
data.tar.gz

uncompress these two tar.gz files  , will help you re-create the deb file

**Comment by mid-kid** [comment]
I mean the `debian` directory used to compile each package. Stuff like `debian/control` and `debian/rules`. It's possible to unpack and repack a deb file but it's not as convenient, or did you make the .deb files manually like that?

**Comment by mid-kid** [comment]
Like, I want to know how each package was built. Now I'm seeing for example that there's a different build of cave story for the cm4, and I'd love to know what the difference between those is. Similarly cool retro term, what's the difference between that and the official debian package?
etc etc

**Comment by cuu** [comment]
it's true that every package made by manually....

everytime I create package/debian/control ,etc by hand

then use a script to build deb file

```
#!/bin/bash

cd `pwd`

if [ -z "$1" ]; then
    echo "no file ,exit"
    exit
fi



PACK=$1
dpkg-deb -Z gzip --build --root-owner-group $PACK || exit

ARCH=`cat ${PACK}/DEBIAN/control  | grep "Architecture" | cut -d " " -f2`
VERSION=`cat ${PACK}/DEBIAN/control  | grep "Version" | cut -d " " -f2`

mv ${PACK}.deb ${PACK}_${VERSION}_${ARCH}.deb
```

**Comment by mid-kid** [comment]
I see! thanks for explaining. If you ever have a simple way where it's possible to build these packages ourselves (for example a script), please publish that. And if you have notes on options you used to build some of these packages, it'd be appreciated if you put them on the github wiki.

Other than that, there's not much I can ask :)
